<?php
/**
 * AT ALL COST ! DO NOT EDIT THIS FILE ! OR YOU'LL BE DAMNED ! (AND HATED)
 */
/*echo "post";

exec(git pull);*/
echo "Autopull script Start \n";
exec ('rm -rf ~/subs/nuitdelinfoihm15');
echo "rm ok\n";
exec ('cd ../ ; git clone git@github.com:IHM15/nuitdelinfoihm15.git');
echo "clone ok\n";
exec ('cp -f ~/subs/nuitdelinfoihm15/php/model/SQLConstants.php.serv ~/subs/nuitdelinfoihm15/php/model/SQLConstants.php');
exec ('cp -rf ~/subs/PhpMyAdmin ~/subs/nuitdelinfoihm15/');
echo "cp ok\n";
echo "Autopull script End\n";
?>