<?php
/**
 * AT ALL COST ! DO NOT EDIT THIS FILE ! OR YOU'LL BE DAMNED ! (AND HATED)
 */
/*echo "post";

exec(git pull);*/
echo "Autopull script Start";
exec ('rm -rf ~/nuitdelinfoihm15');
echo "rm ok";
exec ('git clone git@github.com:IHM15/nuitdelinfoihm15.git');
echo "clone ok";
exec ('cp -f ~/nuitdelinfoihm15/php/model/SQLConstants.php.serv ~/nuitdelinfoihm15/php/model/SQLConstants.php');
echo "cp ok";
echo "Autopull script End";

?>
